### ISSUE TITLE
Push new version to vagrant plugin?

### ISSUE THREAD

**Issue by dcosson** [mrdavidlaing/vagrant-unison#18]
First off, thanks for building this awesome plugin! It seems like unison basically the best/only path to getting 2-way syncing between a host and VM with inotify events.

However, there are a few issues that prevent your current version from being installed in 2016, on the latest Vagrant and OSX versions.

The master branch of this fork ~~https://github.com/dmatora/vagrant-unison by @dmatora (tagged as version 0.0.16)~~ works well for me currently, but it's somewhat annoying to install non-released vagrant plugins.

Can you push that version so we can `vagrant plugin install` it?

**Comment by dcosson** [comment]
UPDATE: I had to make a few more changes to get this working for me, and decided to rename some things to make the namespacing cleaner ("unison" everywhere instead of so many "sync" config options since sync is pretty ambiguous). My repo is [dcosson/vagrant-unison](https://github.com/dcosson/vagrant-unison), I bumped the version to 1.0.0 following symver conventions.

Since there hasn't been any activity in this repo in 2.5 years, if I end up sticking with this plugin for my own dev environment I think I'll push this as a new gem `vagrant-unison2`. I'd love to not do this, if you'd be willing to merge some PR's or make me a maintainer without having to fork it that would be much better. Let me know!

**Comment by zkanda** [comment]
@dcosson Would you mind push that as a new gem? Or it would be good if you can put instruction on how to install that manually. Thanks

**Comment by dcosson** [comment]
It's live as a gem, we've been using it on our team for about a month now.

`vagrant plugin install vagrant-unison2`

For some reason the Listener gem is not working on my El Capitan macbook pro, sometimes I get fsevents many seconds late or not at all. So I always use `vagrant unison-sync-polling`, which works well and doesn't use a ton of CPU for me or anything.
