### ISSUE TITLE
Use net-scp rather than unison

### ISSUE THREAD

**Issue by mrdavidlaing** [mrdavidlaing/vagrant-unison#3]
Since our file watcher tells us exactly which files have changed, we could drop the unison dependancy and just use the net-scp gem to scp the changed files over.

This should also make the sync faster.

**Comment by mrdavidlaing** [comment]
@wizonesolutions - what do you think of using net-scp rather than unison?

**Comment by wizonesolutions** [comment]
That depends — does Unison currently offer two-way sync? Although I don't strictly need that, it's nice to have the option in case I for some reason change synced files on the VM and want the changes to stick.

If it's one-way anyway, something like that'd be nice, but maybe `rsync` would be better. Contrary to its name, `vagrant-rsync` doesn't already offer this.

**Comment by mrdavidlaing** [comment]
Unison does enable 2 way sync; but a sync is only triggered by a change to
a file on the host.

On 26 April 2013 14:51, Kevin Kaland notifications@github.com wrote:

> That depends — does Unison currently offer two-way sync? Although I don't
> strictly need that, it's nice to have the option in case I for some reason
> change synced files on the VM and want the changes to stick.
> 
> If it's one-way anyway, something like that'd be nice, but maybe rsyncwould be better. Contrary to its name,
> vagrant-rsync doesn't already offer this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mrdavidlaing/vagrant-unison/issues/3#issuecomment-17075425
> .

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by mrdavidlaing** [comment]
Oh, and the reason I went with unison rather than rsync is that I couldn't
find an easy way to install rsync on Windows.

An advantage of scp is that its pure ruby, so the plugin will work across
all platforms.

On 26 April 2013 18:28, David Laing david@davidlaing.com wrote:

> Unison does enable 2 way sync; but a sync is only triggered by a change to
> a file on the host.
> 
> On 26 April 2013 14:51, Kevin Kaland notifications@github.com wrote:
> 
> > That depends — does Unison currently offer two-way sync? Although I don't
> > strictly need that, it's nice to have the option in case I for some reason
> > change synced files on the VM and want the changes to stick.
> > 
> > If it's one-way anyway, something like that'd be nice, but maybe rsyncwould be better. Contrary to its name,
> > vagrant-rsync doesn't already offer this.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/mrdavidlaing/vagrant-unison/issues/3#issuecomment-17075425
> > .
> 
> ## 
> 
> David Laing
> Open source @ City Index - github.com/cityindex
> http://davidlaing.com
> Twitter: @davidlaing

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by wizonesolutions** [comment]
I think it'd be useful either way, and if you're motivated to do it, then it's definitely worth it. If I or someone reaaaally doesn't like it they can always fork and scratch their own itch!

**Comment by mrdavidlaing** [comment]
Given that fact that switching away from unison will require a project name change, I think I'll just leave vagrant-unison using unison, and create a new project the uses net-scp

**Comment by wizonesolutions** [comment]
Link me when it's out.

**Comment by cromulus** [comment]
Bidirectional sync would be kinda cool. I'm looking at [lsyncd](https://github.com/axkibe/lsyncd) as a soultion, but, it's built on top of rsync, which is problematic for windows. Have you look at [cwrsync](http://www.rsync.net/resources/howto/windows_rsync.html) ?

net-scp is pure ruby, but getting bidirectional sync working will require some serious work.

**Comment by patcon** [comment]
@cromulus 
cwrsync looks really interesting, but version after 3.0.1 (circa 2011) cost money. They're up to 5.0.4 now, fwiw
http://en.wikipedia.org/wiki/Cwrsync

**Comment by patcon** [comment]
Oops. My bad, up to 4.0.5
http://chocolatey.org/packages/cwrsync

**Comment by cromulus** [comment]
Pants. Oh well. BTW, @mitchellh and company was thinking about using unison way back when for [bidirectional sync](https://github.com/mitchellh/vagrant/issues/91) but moved away from it.

In terms of windows support, perhaps [sshfs](https://code.google.com/p/win-sshfs/)? Also seems a bit like abandonware, been a year since there has been any activity.

**Comment by wizonesolutions** [comment]
Bidirectional sync of some sort would be hot. Even NFS is nothing like running code in the VM's native FS.

**Comment by mrdavidlaing** [comment]
vagrant-unison supports bidirectional sync, BUT a new sync is only
triggered by a file change on the host.

For remote VMs, sshfs just has two much latency on _every_ file operation.
 A sync that only triggers on a file modification is much more performant.

On 15 May 2013 18:02, cromulus notifications@github.com wrote:

> Pants. Oh well. BTW, @mitchellh https://github.com/mitchellh and
> company was thinking about using unison way back when for bidirectional
> sync https://github.com/mitchellh/vagrant/issues/91 but moved away from
> it.
> 
> In terms of windows support, perhaps sshfshttps://code.google.com/p/win-sshfs/?
> Also seems a bit like abandonware, been a year since there has been any
> activity.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mrdavidlaing/vagrant-unison/issues/3#issuecomment-17951818
> .

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by mrdavidlaing** [comment]
@cromulus - With all the options I've investigated (unison, scp, rsync),
the bit I can't solve is how to "watch" for changes on the guest filesystem.

On the host it's easy - just use Listen gem ontop of the Ruby bundled in
Vagrant.

Any ideas how this could be achieved on the guest?

On 15 May 2013 19:11, Kevin Kaland notifications@github.com wrote:

> Bidirectional sync of some sort would be hot. Even NFS is nothing like
> running code in the VM's native FS.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mrdavidlaing/vagrant-unison/issues/3#issuecomment-17955979
> .

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by cromulus** [comment]
I use the guard gem for this.

Sent on the run.

**Comment by patcon** [comment]
`inotifywait`? https://github.com/rvoicilas/inotify-tools/wiki#inotifywait

EDIT: Hm. Seems like it's hacky to daemonize:
https://github.com/rvoicilas/inotify-tools/issues/5#issuecomment-17756009

**Comment by dmatora** [comment]
> Bidirectional sync of some sort would be hot. Even NFS is nothing like running code in the VM's native FS.

latest version of plugin (reachable here http://github.com/dmatora/vagrant-unison )
does realtime bidirectional folder sync
